"""
models/mindmap.py
-----------------
Pydantic models for Mind-map documents stored in MongoDB.

A MindmapModel holds the root of a hierarchical concept tree (MindmapNodeModel)
generated by the LLM for a given Topic.  The node model is self-referencing
and requires ``model_rebuild()`` after class definition.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class MindmapNodeModel(BaseModel):
    """
    A single node within a concept mind-map tree.

    Attributes
    ----------
    id : str
        A client-facing unique identifier for the node (e.g. a slug or UUID).
    title : str
        Short label for the concept represented by this node.
    summary : str
        One-to-three sentence summary of the concept.
    children : List[MindmapNodeModel]
        Nested child nodes.  Empty list for leaf nodes.
    """

    model_config = ConfigDict(populate_by_name=True)

    id: str
    title: str
    summary: str
    children: List["MindmapNodeModel"] = Field(default_factory=list)


# Required for self-referencing Pydantic models
MindmapNodeModel.model_rebuild()


class MindmapModel(BaseModel):
    """
    MongoDB document shape for a Mind-map.

    Attributes
    ----------
    id : Optional[str]
        The MongoDB ``_id`` serialised as a plain string.
    topic_id : str
        Foreign-key reference to the parent ``TopicModel._id``.
    root : MindmapNodeModel
        The root node of the concept tree.
    created_at : datetime
        UTC timestamp of document creation.
    """

    model_config = ConfigDict(populate_by_name=True)

    id: Optional[str] = Field(default=None, alias="_id")
    topic_id: str
    root: MindmapNodeModel
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
